# Author: Ringlet Valentin
from .Problem001 import solve
from .Problem002 import solve
from .Problem003 import solve
from .Problem004 import solve
from .Problem005 import solve
from .Problem006 import solve
from .Problem007 import solve
from .Problem008 import solve
from .MethodLibrary import *